### ISSUE TITLE
Add new styles for the welcome image

### ISSUE THREAD

**Issue by jlasoc1** [ddd-crew/welcome-to-ddd#4]
Hello @NTCoding @Max-Git @Baasie !

I'm trying to post a PR with a new style for this repo (I'm almost sure that you will love it), but I don't have access to do it :( 
can you help me with that?

**Comment by Max-Git** [comment]
Hi Javiera!
I gave you access rights, let me know if it's ok!

**Comment by jlasoc1** [comment]
all good, thanks !
